version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - db
    command: yarn start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    depends_on:
      - backend
    command: npm run start

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}



volumes:
  postgres_data: